export const CREATE_LITTER = "CREATE_LITTER";
export const LOAD_LITTERS_SUCCESS = "LOAD_LITTERS_SUCCESS";
export const LOAD_KITTENS_SUCCESS = "LOAD_KITTENS_SUCCESS";
export const CREATE_LITTER_SUCCESS = "CREATE_LITTER_SUCCESS";
export const UPDATE_LITTER_SUCCESS = "UPDATE_LITTER_SUCCESS";
export const CREATE_KITTEN_SUCCESS = "CREATE_KITTEN_SUCCESS";
export const UPDATE_KITTEN_SUCCESS = "UPDATE_KITTEN_SUCCESS";
